openapi: 3.0.0
info:
  title: API Đặt Sân Thể Thao
  version: 1.0.0
  description: API cho hệ thống đặt sân bóng đá
servers:
  - url: http://localhost:5000/api
paths:
  /auth/register:
    post:
      summary: Đăng ký người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hoTen:
                  type: string
                email:
                  type: string
                matKhau:
                  type: string
                soDienThoai:
                  type: string
      responses:
        '201':
          description: Đăng ký thành công
        '400':
          description: Lỗi dữ liệu đầu vào
  /auth/login:
    post:
      summary: Đăng nhập người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                matKhau:
                  type: string
      responses:
        '200':
          description: Đăng nhập thành công
        '401':
          description: Sai thông tin đăng nhập
  /danhsachsan:
    get:
      summary: Lấy danh sách sân bóng
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách sân bóng
  /sanbong/{id}:
    get:
      summary: Lấy thông tin sân bóng theo id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thông tin sân bóng
        '404':
          description: Không tìm thấy sân bóng
  /datsan:
    post:
      summary: Đặt sân
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sanBong:
                  type: string
                khungGio:
                  type: string
                ghiChu:
                  type: string
      responses:
        '201':
          description: Đặt sân thành công
        '400':
          description: Lỗi đặt sân
  /danhsachdadat:
    get:
      summary: Lấy danh sách đặt sân theo user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách đặt sân
  /addsan:
    post:
      summary: Thêm sân bóng (admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tenSan:
                  type: string
                Danhmuc:
                  type: string
                loaiSan:
                  type: string
                  enum: ['2 người','5 người', '7 người', '11 người']
                diaChi:
                  type: string
                hinhAnh:
                  type: string
                giaTheoKhungGio:
                  type: array
                  items:
                    type: object
                    properties:
                      khungGio:
                        type: string
                      gia:
                        type: number
                      Trangthai:
                        type: string
                        enum: ['Còn sân', 'Hết sân']
                tinhTrang:
                  type: string
                  enum: ['Đang hoạt động', 'Bảo trì']
      responses:
        '201':
          description: Thêm sân thành công
        '403':
          description: Không có quyền
  /suasan/{id}:
    put:
      summary: Sửa sân bóng (admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tenSan:
                  type: string
                Danhmuc:
                  type: string
                loaiSan:
                  type: string
                  enum: ['2 người','5 người', '7 người', '11 người']
                diaChi:
                  type: string
                hinhAnh:
                  type: string
                giaTheoKhungGio:
                  type: array
                  items:
                    type: object
                    properties:
                      khungGio:
                        type: string
                      gia:
                        type: number
                      Trangthai:
                        type: string
                        enum: ['Còn sân', 'Hết sân']
                tinhTrang:
                  type: string
                  enum: ['Đang hoạt động', 'Bảo trì']
      responses:
        '200':
          description: Cập nhật sân thành công
        '403':
          description: Không có quyền
  /xoasan/{id}:
    delete:
      summary: Xóa sân bóng (admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Xóa sân thành công
        '403':
          description: Không có quyền
  /{id}/xacnhandatsan:
    put:
      summary: Admin xác nhận đặt sân
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                daXacNhan:
                  type: boolean
                trangThaiThanhToan:
                  type: string
      responses:
        '200':
          description: Xác nhận thành công
        '403':
          description: Không có quyền
  /xoauser/{id}:
    delete:
      summary: Xóa người dùng (admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Xóa người dùng thành công
        '403':
          description: Không có quyền
  /updateuser/{id}:
    put:
      summary: Sửa thông tin người dùng (admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hoTen:
                  type: string
                soDienThoai:
                  type: string
                trangThai:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Cập nhật thành công
        '403':
          description: Không có quyền
  /user:
    get:
      summary: Lấy danh sách người dùng (admin hoặc user)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lấy danh sách người dùng thành công
  /cap-nhat-thong-tin:
    put:
      summary: Cập nhật thông tin cá nhân
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hoTen:
                  type: string
                email:
                  type: string
                soDienThoai:
                  type: string
      responses:
        '200':
          description: Cập nhật thành công
  /doi-mat-khau:
    put:
      summary: Đổi mật khẩu
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matKhauCu:
                  type: string
                matKhauMoi:
                  type: string
      responses:
        '200':
          description: Đổi mật khẩu thành công
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
